### PR TITLE
Fixes to compile with dear imgui 1.80 + warning fixes.

### PR DESCRIPTION
**Pull request by ocornut**
Minor fixes (your code previously used alpha table api some of which had changed)

Also note that for right/bottom align -FLT_MIN is more correct than -1.0f which will remove an extra pixel) hence those changes.

Note that I didn't yet run `ImFileDialog`, this is merely putting some fixes out ahead for users who will try to use it with dear imgui `master`. I'm also getting two std::string related warning I haven't inspected yet.

### CODE REVIEW

**Comment by ocornut** [comment]
Now ran it and force-pushed some fixes for column policy.

Since there are 3 columns and the intent seems to have 2 of them not resizable it's not meaningful to set the `ImGuiTableFlags_Resizable` flag, but it could be brought back if removing `ImGuiTableColumnFlags_NoResize` from the secondary columns.

**Comment by dfranx** [comment]
Thanks for the PR, merged!
And thank you for the tips, will keep them in mind!

**Comment by SadE54** [comment]
LastitemRect was removed from imgui_internal.h in 1.84 :-/
Is it possible to add a commit to get the file dialog working with 1.84+ please ?

**Comment by ocornut** [comment]
See https://github.com/ocornut/imgui/discussions/4526#discussioncomment-1308122

**Pull request merged**
